version: '3.8'

services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/app/lookback:/usr/src/app
    command: 'npx next dev'
    ports:
      - "3000:3000"

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    tty: true
    volumes:
      - ./api:/go/src