services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
    tty: true
    volumes:
      - ./api:/go/src/app
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/app/lookback:/usr/src/app
    command: 'npx next dev'
    ports:
      - "3000:3000"
volumes:
  mysql-db:
    driver: local