FROM --platform=linux/x86_64 golang:1.18-alpine

WORKDIR /go/src/
COPY . .

RUN apk upgrade --update && \
    apk --no-cache add git gcc musl-dev

RUN go mod tidy

RUN go get github.com/gin-gonic/gin \
    github.com/jinzhu/gorm \
    github.com/jinzhu/gorm/dialects/mysql \
    github.com/joho/godotenv \
    github.com/resendlabs/resend-go

RUN go mod tidy

RUN go get -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest